<?php

declare(strict_types=1);

/*
 * This file is part of the artigo/versioned-cache package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Artigo\Cache\Adapter;

use Artigo\Cache\Exception\InvalidArgumentException;
use Psr\Cache\CacheItemPoolInterface;
use Symfony\Component\Cache\Adapter\AbstractTagAwareAdapter;
use Symfony\Component\Cache\CacheItem;
use Symfony\Component\Cache\Exception\CacheException;
use Symfony\Component\Cache\Marshaller\DefaultMarshaller;
use Symfony\Component\Cache\Marshaller\MarshallerInterface;

/**
 * Tag invalidation that costs the same whether three items match or three
 * million.
 *
 * Symfony's RedisTagAwareAdapter keeps a SET per tag and, when the tag is
 * invalidated, walks that SET deleting every member - one blocking Lua loop
 * whose length is the number of matched items, during which the single
 * threaded server does nothing else.
 *
 * This adapter never builds that index. An invalidation appends **one rule**
 * to a Redis stream and returns; the work of noticing is deferred to whoever
 * reads next. Every item is written with the stream's last entry id at the
 * time - its watermark - and a read evaluates only the rules newer than that
 * watermark against the item's own tags. A stale item is unlinked as it is
 * read and, failing that, expires by its TTL.
 *
 * Ordering is causal rather than clock based: stream ids are generated by the
 * node that owns the stream and are monotonic, so nothing anywhere compares
 * two clocks.
 *
 *     $redis = RedisAdapter::createConnection('redis://127.0.0.1');
 *     $pool = new VersionedRedisTagAwareAdapter($redis);
 *
 *     $pool->invalidateTags(['articles']);   // 4 commands, whatever matches
 *
 * An item is a hash written with HSETEX (Redis 8.0), which sets the fields
 * and their expiry in one command: no script on the write path, and no way
 * for the data to land without the TTL that keeps it from outliving the
 * rules. The key itself is given the same TTL so a volatile-* eviction policy
 * still sees it as evictable.
 *
 * The rules stream, on the other hand, carries no TTL, as Symfony's tag Sets
 * do not: under `volatile-*` or `noeviction` it is never evicted, and one of
 * those is the policy to run. Under `allkeys-*` it can go, and the read path
 * then fails safe - an item stamped with a rule the stream no longer
 * remembers is a miss, never a stale hit - at the price of recomputing the
 * pool once.
 *
 * The watermark is the stream's head at write time, as Symfony's own tag
 * semantics require: an item committed after an invalidation is fresh, even
 * when its value was computed before it (TagAwareTestTrait pins this). The
 * window between computing a value and writing it is therefore open here as
 * it is in every write-back cache.
 *
 * The rule set is compacted - the newest rule per tag - and, given a cache
 * pool, shared by the workers of a server, so a fresh process (every request,
 * under PHP-FPM) adopts it instead of loading the whole stream before its
 * first hit (see SharedRules). APCu is the default pool where it is enabled;
 * pass false as $rulesCache to keep the set per instance.
 *
 * What it is worse at, and there is no getting around any of it:
 *
 * - **Memory comes back lazily.** An invalidated item holds its RAM until a
 *   read unlinks it or its TTL runs out. Reading a fully invalidated set is
 *   roughly twice the cost of reading a live one.
 * - **Invalidation becomes visible within `rulesCacheMs`**, because the rule
 *   set is cached in the process for that long. Pass 0 for exact reads, at
 *   the price of loading the rules on every one.
 * - **`$rulesRetentionSeconds` is the maximum item lifetime**, not only the
 *   default. An item must never outlive the rule that made it stale, or it
 *   would come back from the dead once that rule is trimmed away, so a longer
 *   TTL is capped and a warning is logged.
 * - **No tag enumeration.** There is no index to enumerate.
 */
final class VersionedRedisTagAwareAdapter extends AbstractTagAwareAdapter
{
    /**
     * What Symfony puts between a namespace and a key. AbstractTagAwareAdapter
     * only exposes its own NS_SEPARATOR from 7.3 on, and this package supports
     * 6.4, so the value lives here rather than being borrowed.
     */
    private const NAMESPACE_SEPARATOR = ':';

    private const FIELD_VALUE = 'v';
    private const FIELD_TAGS = 't';
    private const FIELD_MARK = 'm';

    /**
     * How long a worker holding no rules waits for the one elected to load
     * the stream before loading it on its own: the cold start of a server
     * whose shared pool was just emptied, where every request would otherwise
     * load the whole stream at once. In milliseconds.
     */
    private const COLD_WAIT_MS = 250;

    /**
     * How often that worker looks whether the load has landed, in milliseconds.
     */
    private const COLD_POLL_MS = 2;

    /**
     * Appends one rule and keeps the stream from growing without bound. A
     * rule that matches the whole pool makes every older rule redundant, and
     * the stream is trimmed to it; otherwise rules older than the longest
     * possible item lifetime are dropped, having nothing left alive to match.
     *
     * Each rule records whether it opened the stream: NOMKSTREAM refuses to
     * create one, so a nil reply says there was none, and the rule is
     * appended again as the first of a new stream. A reader that holds an
     * item stamped older than an opening rule knows the stream has lost
     * what the item once saw (see InvalidationRules).
     *
     * The stream is the only record that an invalidation ever happened, so it
     * carries no TTL: under a volatile-* policy that keeps it out of the
     * eviction pool altogether, where a TTL would make it a candidate like any
     * item. The PERSIST is unconditional, so the stream carries no expiry
     * however it came to exist. Items cannot outlive the rules anyway: their
     * TTL is capped to the retention, and the trim above drops only what
     * nothing alive can match.
     *
     * The one script in this adapter, because the trim needs the id XADD just
     * generated. Sent as a body: an invalidation is rare, and a body needs no
     * script cache to be intact.
     */
    private const SCRIPT_INVALIDATE = <<<'LUA'
        local retention = tonumber(ARGV[2])
        local id = redis.call('XADD', KEYS[1], 'NOMKSTREAM', '*', 't', ARGV[1], 'first', '0')

        if not id then
            id = redis.call('XADD', KEYS[1], '*', 't', ARGV[1], 'first', '1')
        end

        if ARGV[3] == '1' then
            redis.call('XTRIM', KEYS[1], 'MINID', id)
        else
            local ms = tonumber(string.match(id, '^(%d+)'))
            redis.call('XTRIM', KEYS[1], 'MINID', ms - retention)
        end

        redis.call('PERSIST', KEYS[1])

        return id
        LUA;

    private MarshallerInterface $marshaller;
    private string $rulesKey;
    private string $poolNamespace;
    private ?InvalidationRules $rules = null;
    private ?float $rulesReadAt = null;

    /**
     * This adapter appended a rule the held set has not seen yet: the next
     * read fetches the delta whatever the window or the shared set say, so a
     * process always sees its own invalidations at once.
     */
    private bool $rulesDirty = false;

    /**
     * The set shared with the other workers of this server; null when the
     * caller opted out, or gave no pool and APCu is not there.
     */
    private ?SharedRules $sharedRules;

    private bool $ttlWarned = false;

    /**
     * @param int                               $rulesRetentionSeconds how long rules - and therefore items - may live
     * @param int                               $rulesCacheMs          how long a loaded rule set may be reused before it is refreshed
     * @param CacheItemPoolInterface|false|null $rulesCache            where the workers of a server share the rule set (see SharedRules): a pool, false for none, null for APCu where it is enabled
     */
    public function __construct(
        private readonly \Redis|\RedisArray|\RedisCluster|\Relay\Relay|\Relay\Cluster $redis,
        string $namespace = '',
        int $defaultLifetime = 0,
        ?MarshallerInterface $marshaller = null,
        private readonly int $rulesRetentionSeconds = 2_592_000,
        private readonly int $rulesCacheMs = 1_000,
        CacheItemPoolInterface|false|null $rulesCache = null,
    ) {
        if ($rulesRetentionSeconds < 1) {
            throw new InvalidArgumentException(\sprintf('Argument "$rulesRetentionSeconds" must be a positive number of seconds, %d given.', $rulesRetentionSeconds));
        }

        if ($rulesCacheMs < 0) {
            throw new InvalidArgumentException(\sprintf('Argument "$rulesCacheMs" must not be negative, %d given.', $rulesCacheMs));
        }

        self::rejectClientSideEncoding($redis);

        parent::__construct($namespace, $defaultLifetime);

        $this->marshaller = $marshaller ?? new DefaultMarshaller();
        $this->poolNamespace = '' === $namespace ? '' : $namespace.self::NAMESPACE_SEPARATOR;
        $this->rulesKey = $this->poolNamespace.'@rules';
        $this->sharedRules = SharedRules::of($rulesCache, $this->rulesKey, $redis);
    }

    /**
     * One appended rule, and we are done - the reason this adapter exists.
     *
     * The tags arrive as written rather than as index ids: there is no index,
     * so there is nothing to name.
     */
    public function invalidateTags(array $tags): bool
    {
        if ([] === $tags) {
            return false;
        }

        return $this->doInvalidate(InvalidationRules::strings(array_unique(InvalidationRules::strings($tags))));
    }

    public function reset(): void
    {
        parent::reset();

        // the rule set is shared truth with a bounded staleness, not request
        // state: keep it and let the next read fetch what is new
        $this->rulesReadAt = null;
    }

    /**
     * @param array<string, array{value: mixed, tags?: list<string>, meta?: string}> $values
     * @param array<string, list<string>>                                            $addTagData
     * @param array<string, list<string>>                                            $removeTagData
     *
     * @return list<string>
     */
    protected function doSave(array $values, int $lifetime, array $addTagData = [], array $removeTagData = []): array
    {
        $payloads = [];
        $tags = [];

        foreach ($values as $id => $value) {
            $tags[$id] = InvalidationRules::strings($value['tags'] ?? []);
            unset($value['tags']);
            $payloads[$id] = $value;
        }

        if (!$marshalled = $this->marshaller->marshall($payloads, $failed)) {
            return InvalidationRules::strings($failed ?? []);
        }

        if ($lifetime > $this->rulesRetentionSeconds && !$this->ttlWarned) {
            $this->ttlWarned = true;
            $this->logger?->warning('A lifetime of {lifetime}s is above rulesRetentionSeconds ({retention}s) and was capped to it; raise the retention to keep items longer.', [
                'lifetime' => $lifetime,
                'retention' => $this->rulesRetentionSeconds,
            ]);
        }

        // an item must never outlive the rules: no lifetime, or one beyond the
        // retention, becomes the retention
        $ttl = ($lifetime <= 0 || $lifetime > $this->rulesRetentionSeconds ? $this->rulesRetentionSeconds : $lifetime) * 1000;

        // read once for the whole batch: a rule appended between this and the
        // writes below simply looks newer than the items, which invalidates
        // them - the safe direction to be wrong in
        $mark = $this->watermark();
        $calls = [];

        foreach ($marshalled as $id => $value) {
            $id = (string) $id;

            if (!\is_string($value)) {
                $failed[] = $id;

                continue;
            }

            $calls[] = $this->command('HSETEX', $id, 'PX', (string) $ttl, 'FIELDS', '3', self::FIELD_VALUE, $value, self::FIELD_TAGS, json_encode($tags[$id], \JSON_THROW_ON_ERROR), self::FIELD_MARK, $mark);
            // the fields expire on their own; the key's TTL is for the eviction policy
            $calls[] = $this->command('PEXPIRE', $id, (string) $ttl);
        }

        $results = $this->pipeline($calls);
        $index = 0;

        foreach ($marshalled as $id => $value) {
            if (!\is_string($value)) {
                continue;
            }

            if (1 !== ($results[2 * $index] ?? null)) {
                $failed[] = (string) $id;
            }

            ++$index;
        }

        return InvalidationRules::strings($failed ?? []);
    }

    /**
     * @param list<string> $ids
     *
     * @return iterable<string, array<string, mixed>>
     */
    protected function doFetch(array $ids): iterable
    {
        if ([] === $ids) {
            return;
        }

        // without the rules, fresh cannot be told from stale: every item is a
        // miss for now, and nothing is unlinked on a verdict we cannot reach
        if (null === $rules = $this->rules()) {
            return;
        }

        $fields = [self::FIELD_VALUE, self::FIELD_TAGS, self::FIELD_MARK];
        $calls = [];

        foreach ($ids as $id) {
            $calls[] = ['hMGet', $id, $fields];
        }

        $rows = $this->pipeline($calls);
        $stale = [];

        foreach ($ids as $index => $id) {
            $row = $rows[$index] ?? null;

            if (!\is_array($row) || !\is_string($row[self::FIELD_VALUE] ?? null) || !\is_string($row[self::FIELD_TAGS] ?? null)) {
                continue;
            }

            $tags = InvalidationRules::strings(json_decode($row[self::FIELD_TAGS], true));
            $mark = $row[self::FIELD_MARK] ?? null;

            if ($rules->invalidates($id, $tags, \is_string($mark) ? $mark : InvalidationRules::NONE)) {
                $stale[] = $id;

                continue;
            }

            try {
                $value = $this->marshaller->unmarshall($row[self::FIELD_VALUE]);
            } catch (\Exception) {
                $stale[] = $id;

                continue;
            }

            if (!\is_array($value) || !\array_key_exists('value', $value)) {
                $stale[] = $id;

                continue;
            }

            $item = ['value' => $value['value'], 'tags' => $tags];

            if (\array_key_exists('meta', $value)) {
                $item['meta'] = $value['meta'];
            }

            yield $id => $item;
        }

        if ([] !== $stale) {
            // the lazy half of the bargain: a stale item costs its reader one
            // unlink, and nobody else anything at all
            $this->doDelete($stale);
        }
    }

    /**
     * Reads the tags and the watermark only: the answer needs no value.
     */
    protected function doHave(string $id): bool
    {
        if (null === $rules = $this->rules()) {
            return false;
        }

        $row = $this->redis->hMGet($id, [self::FIELD_TAGS, self::FIELD_MARK]);

        if (!\is_array($row) || !\is_string($row[self::FIELD_TAGS] ?? null)) {
            return false;
        }

        $mark = $row[self::FIELD_MARK] ?? null;

        if ($rules->invalidates($id, InvalidationRules::strings(json_decode($row[self::FIELD_TAGS], true)), \is_string($mark) ? $mark : InvalidationRules::NONE)) {
            $this->doDelete([$id]);

            return false;
        }

        return true;
    }

    /**
     * @param list<string> $ids
     */
    protected function doDelete(array $ids): bool
    {
        if ([] === $ids) {
            return true;
        }

        try {
            $this->redis->unlink($ids);
        } catch (\Exception $e) {
            CacheItem::log($this->logger, 'Failed to delete items: '.$e->getMessage(), ['exception' => $e, 'cache-adapter' => get_debug_type($this)]);

            return false;
        }

        return true;
    }

    /**
     * There is no tag index to clean up when an item goes, so nothing is
     * yielded and the parent skips the relation bookkeeping entirely. The
     * default reads every item first to learn its tags; we can just delete.
     *
     * @param list<string> $ids
     *
     * @return iterable<string, list<string>>
     */
    protected function doDeleteYieldTags(array $ids): iterable
    {
        if (!$this->doDelete($ids)) {
            // tell the caller, which retries the ids one by one
            throw new CacheException('Failed to delete the items.');
        }

        yield from [];
    }

    /**
     * @param array<string, list<string>> $tagData
     */
    protected function doDeleteTagRelations(array $tagData): bool
    {
        return true;
    }

    /**
     * @param list<string> $tagIds
     */
    protected function doInvalidate(array $tagIds): bool
    {
        return $this->addRule($tagIds, null);
    }

    /**
     * Symfony hands a key prefix here, not always the whole pool: clearing
     * "foo" must leave "barfoo" where it is. A prefix rule says so in one
     * appended entry, where an eager adapter has to walk the keyspace.
     */
    protected function doClear(string $namespace): bool
    {
        return $this->addRule([], $namespace);
    }

    /**
     * @param list<string> $tags
     */
    private function addRule(array $tags, ?string $prefix): bool
    {
        $rule = [];

        if ([] !== $tags) {
            $rule['t'] = $tags;
        }

        if (null !== $prefix) {
            $rule['p'] = $prefix;
        }

        // a rule covering the whole pool leaves nothing for an older rule to
        // say, so the stream can be trimmed back to it
        $subsumes = null !== $prefix && [] === $tags && $prefix === $this->poolNamespace;

        $arguments = [
            $this->rulesKey,
            json_encode($rule, \JSON_THROW_ON_ERROR),
            $this->rulesRetentionSeconds * 1000,
            $subsumes ? '1' : '0',
        ];

        try {
            $result = $this->redis->eval(self::SCRIPT_INVALIDATE, $arguments, 1);
        } catch (\Exception $e) {
            CacheItem::log($this->logger, 'Failed to append the invalidation rule: '.$e->getMessage(), ['exception' => $e, 'cache-adapter' => get_debug_type($this)]);

            return false;
        }

        if (!\is_string($result)) {
            CacheItem::log($this->logger, 'Failed to append the invalidation rule.', ['cache-adapter' => get_debug_type($this)]);

            return false;
        }

        // what we hold is behind the rule we just wrote; the next read fetches
        // it, and whatever anyone else appended meanwhile, in one range -
        // whatever the window or the shared set say
        $this->rulesDirty = true;

        return true;
    }

    /**
     * The rules stream's last entry id, or "0-0" when it has none.
     *
     * A rule set fetched within the cache window already knows it, at no
     * round trip: a rule appended since makes the stamp older than the
     * stream's head, which invalidates the item - the safe direction.
     */
    private function watermark(): string
    {
        if ($this->rulesCacheMs > 0 && null !== ($rules = $this->rules()) && $this->rulesAreFresh()) {
            return $rules->last();
        }

        try {
            $last = $this->redis->xRevRange($this->rulesKey, '+', '-', 1);
        } catch (\Exception $e) {
            // an item stamped 0-0 has seen no rules, so every rule applies to
            // it: we lose the item, never serve it past its invalidation
            CacheItem::log($this->logger, 'Failed to read the invalidation watermark: '.$e->getMessage(), ['exception' => $e, 'cache-adapter' => get_debug_type($this)]);

            return InvalidationRules::NONE;
        }

        if (!\is_array($last) || [] === $last) {
            return InvalidationRules::NONE;
        }

        $id = array_key_first($last);

        return \is_string($id) ? $id : InvalidationRules::NONE;
    }

    /**
     * The rule set, refreshed at most every $rulesCacheMs - incrementally,
     * from the last id it holds, and shared with the other workers of this
     * server where a pool allows (see SharedRules).
     *
     * In order: the held set while it is fresh; the shared set, adopted
     * unless what is held is newer, and final when it is fresh - no round
     * trip; otherwise a refresh: one XRANGE from the last id held, absorbed,
     * stamped and stored for the next worker. Where several workers cross the
     * window together, one is elected to refresh and the others keep the set
     * they hold for this read - one refresh away from exact, never blocked. A
     * worker that holds nothing, on a server whose pool was just emptied,
     * waits for the leader's load for a bounded time (COLD_WAIT_MS) rather
     * than join a herd of full loads, then loads on its own. Exact reads
     * ($rulesCacheMs = 0) elect nobody: every read refreshes.
     *
     * When it cannot be refreshed the last known set is reused: reporting "no
     * rules" would let an invalidated item read as fresh, which is the one
     * answer this must never give. With nothing to fall back on it answers
     * null, and the read path treats every item as a miss until the rules are
     * back - without unlinking anything on a verdict it could not reach.
     */
    private function rules(): ?InvalidationRules
    {
        if (null !== $this->rules && !$this->rulesDirty && $this->rulesAreFresh()) {
            return $this->rules;
        }

        // not after our own invalidation: the shared set cannot have it yet,
        // and a process must see what it just invalidated
        $shared = $this->rulesDirty ? null : $this->sharedRules;
        $leader = null;

        if (null !== $shared) {
            if ($this->adoptSharedRules($shared) && $this->rulesAreFresh()) {
                return $this->rules;
            }

            if ($this->rulesCacheMs > 0) {
                $leader = $shared->lead() ? $shared : null;

                if (null === $leader) {
                    // another worker is refreshing right now: what we hold is
                    // one refresh away from exact, good enough for this read
                    if (null !== $this->rules) {
                        return $this->rules;
                    }

                    // holding nothing, wait for the leader's load instead
                    if ($this->awaitSharedRules($shared)) {
                        return $this->rules;
                    }
                }
            }
        }

        try {
            $rules = $this->rules ?? new InvalidationRules($this->poolNamespace, $this->rulesRetentionSeconds * 1000);
            $from = $rules->last();

            try {
                $entries = $this->redis->xRange($this->rulesKey, InvalidationRules::NONE === $from ? '-' : $from, '+');
            } catch (\Exception $e) {
                CacheItem::log($this->logger, 'Failed to load the invalidation rules: '.$e->getMessage(), ['exception' => $e, 'cache-adapter' => get_debug_type($this)]);

                return $this->rules;
            }

            if (!\is_array($entries)) {
                CacheItem::log($this->logger, 'Failed to load the invalidation rules.', ['cache-adapter' => get_debug_type($this)]);

                return $this->rules;
            }

            $rules->absorb($entries);
            $readAtMs = microtime(true) * 1000;

            $this->rules = $rules;
            $this->rulesReadAt = $readAtMs;
            $this->rulesDirty = false;

            $this->sharedRules?->store($rules, $readAtMs);

            return $rules;
        } finally {
            $leader?->release();
        }
    }

    /**
     * Takes over the set another worker shared, unless what is held is newer.
     * True when a set was adopted - fresh or not - false when there was
     * nothing to adopt.
     */
    private function adoptSharedRules(SharedRules $shared): bool
    {
        if (null === $loaded = $shared->load($this->poolNamespace, $this->rulesRetentionSeconds * 1000)) {
            return false;
        }

        [$rules, $readAtMs] = $loaded;

        if (null !== $this->rules && InvalidationRules::isNewerId($this->rules->last(), $rules->last())) {
            return false;
        }

        $this->rules = $rules;
        $this->rulesReadAt = $readAtMs;

        return true;
    }

    /**
     * Waits, briefly, for the worker elected to load the stream to share it:
     * looks every COLD_POLL_MS for at most COLD_WAIT_MS, and gives up early
     * when the leader has gone without leaving a set. True when a set was
     * adopted.
     */
    private function awaitSharedRules(SharedRules $shared): bool
    {
        $deadline = microtime(true) + self::COLD_WAIT_MS / 1000;

        do {
            usleep(self::COLD_POLL_MS * 1000);

            if ($this->adoptSharedRules($shared)) {
                return true;
            }
        } while ($shared->isRefreshing() && microtime(true) < $deadline);

        return false;
    }

    private function rulesAreFresh(): bool
    {
        return null !== $this->rulesReadAt && microtime(true) * 1000 - $this->rulesReadAt < $this->rulesCacheMs;
    }

    /**
     * A write command by its wire name, addressed by key where a cluster
     * routes by it.
     *
     * Everything travels as a string on purpose. phpredis marshals the
     * integers of its typed methods through a C long, which is 32 bits wide
     * on Windows, and a millisecond TTL a month long does not survive the
     * trip: HSETEX refuses the expiry outright and PEXPIRE, handed what is
     * now a negative number, deletes the key it was meant to keep. The
     * protocol is strings anyway. php-library's own function loader says the
     * same thing about its FCALL arguments, having got there first.
     *
     * @return array{0: string, ...}
     */
    private function command(string $command, string $key, string ...$arguments): array
    {
        $arguments = array_values($arguments);

        return $this->redis instanceof \RedisCluster || $this->redis instanceof \Relay\Cluster
            ? ['rawCommand', $key, $command, $key, ...$arguments]
            : ['rawCommand', $command, $key, ...$arguments];
    }

    /**
     * Runs [method, ...arguments] calls through one round trip where the
     * connection allows it, and one at a time where it does not. The answers
     * come back in the order of the calls.
     *
     * @param list<array{0: string, ...}> $calls
     *
     * @return list<mixed>
     */
    private function pipeline(array $calls): array
    {
        if ($this->redis instanceof \RedisArray) {
            // no raw command of its own, and nothing to pipeline across nodes:
            // every call goes to whichever node owns the key it names
            $results = [];

            foreach ($calls as $call) {
                $method = array_shift($call);

                if ('rawCommand' !== $method) {
                    $results[] = $this->redis->{$method}(...$call);

                    continue;
                }

                $arguments = [];

                foreach ($call as $argument) {
                    $arguments[] = \is_scalar($argument) ? (string) $argument : '';
                }

                // [command, key, ...]: the key is what says which node to ask
                $results[] = $this->onOwningNode($arguments[1] ?? '', ...$arguments);
            }

            return $results;
        }

        // a single node speaks pipelining; a cluster, or a connection that
        // simply declines, gets one command at a time
        $pipe = null;

        if ($this->redis instanceof \Redis) {
            $pipe = $this->redis->multi(\Redis::PIPELINE);
        } elseif ($this->redis instanceof \Relay\Relay) {
            $pipe = $this->redis->multi(\Relay\Relay::PIPELINE);
        }

        if (!\is_object($pipe)) {
            $results = [];

            foreach ($calls as $call) {
                $method = array_shift($call);
                $results[] = $this->redis->{$method}(...$call);
            }

            return $results;
        }

        foreach ($calls as $call) {
            $method = array_shift($call);
            $pipe->{$method}(...$call);
        }

        $results = $pipe->exec();

        if (!\is_array($results) || \count($results) !== \count($calls)) {
            // the connection went away under the batch: every call failed
            return array_fill(0, \count($calls), false);
        }

        return array_values($results);
    }

    /**
     * Sends one raw command to the node of a RedisArray that owns the key,
     * the array itself having no rawCommand() to route for us.
     */
    private function onOwningNode(string $key, string ...$arguments): mixed
    {
        \assert($this->redis instanceof \RedisArray);

        $node = $this->redis->_instance($this->redis->_target($key));

        return $node instanceof \Redis ? $node->rawCommand(...$arguments) : false;
    }

    /**
     * The adapter writes raw hash fields and reads them back with HMGET, so a
     * client that serializes or compresses values on its own would decode
     * what it never encoded. Symfony's marshallers are where that belongs. A
     * lazy proxy is left alone, as RedisTagAwareAdapter leaves it.
     */
    private static function rejectClientSideEncoding(\Redis|\RedisArray|\RedisCluster|\Relay\Relay|\Relay\Cluster $redis): void
    {
        $isRelay = $redis instanceof \Relay\Relay || $redis instanceof \Relay\Cluster;

        if (!$isRelay && !\in_array($redis::class, [\Redis::class, \RedisArray::class, \RedisCluster::class], true)) {
            return;
        }

        $checks = $isRelay
            ? [
                ['serializer', \Relay\Relay::OPT_SERIALIZER, \Relay\Relay::SERIALIZER_NONE],
                ['compression', \Relay\Relay::OPT_COMPRESSION, \Relay\Relay::COMPRESSION_NONE],
            ]
            : [['serializer', \Redis::OPT_SERIALIZER, \Redis::SERIALIZER_NONE]];

        if (!$isRelay && \defined('Redis::OPT_COMPRESSION')) {
            $checks[] = ['compression', \Redis::OPT_COMPRESSION, \Redis::COMPRESSION_NONE];
        }

        foreach ($checks as [$name, $option, $none]) {
            $value = $redis->getOption($option);

            // a RedisArray answers once per node
            foreach (\is_array($value) ? $value : [$value] as $v) {
                if ($none !== $v) {
                    throw new InvalidArgumentException(\sprintf('redis %s must be disabled when using "%s", use a marshaller instead.', $name, self::class));
                }
            }
        }
    }
}
